name: CI

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
    - uses: actions/checkout@v6

    - name: Build
      run: |
        python3 -m venv venv
        source venv/bin/activate
        pip install -r requirements.txt
        ./build.py

    - name: Upload repo artifact
      if: github.event_name == 'push' && github.ref_name == 'main'
      uses: actions/upload-pages-artifact@v5
      with:
        path: dist/

    - name: Deploy to GitHub Pages
      if: github.event_name == 'push' && github.ref_name == 'main'
      uses: actions/deploy-pages@v5